# Generated by Django 5.1.4 on 2024-12-22 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_choice_delete_result_remove_question_option1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
